/*
 * Stoatworks Labs - About window data for Fax.
 *
 * PROVISIONAL HAND COPY, written 2026-09-25 from teletext's generated header.
 * The fleet's copies are GENERATED by stoatworks-backend/scripts/sync-about.py
 * from the website's projects.json, and this one will be replaced by that sync
 * when the plugin is registered. Until then:
 *
 *   - `guide` is empty: no user guide exists yet, and an empty link is left out
 *     of the host's buttons rather than shown as a button that opens a 404.
 *   - `page` is empty for the same reason: the project is not on the website.
 *   - `repo` is the intended home. It does not exist yet either; the brief says
 *     a link may point there.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Fax";
    inline constexpr auto slug = "fax";
    inline constexpr auto hook = "A Group 3 fax over a noisy line, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/fax";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
